"""add reminders

Revision ID: 26628ce88d22
Revises: e0077e6e271a
Create Date: 2025-12-13 13:58:14.676920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26628ce88d22'
down_revision = 'e0077e6e271a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('reminder_date', sa.String(length=10), nullable=False),
    sa.Column('notify_days_before', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contactos.contactos_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    # ### end Alembic commands ###
