"""empty message

Revision ID: a49179a73959
Revises: e3ae0fcaa6d8
Create Date: 2025-12-06 20:41:32.521243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49179a73959'
down_revision = 'e3ae0fcaa6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termino_busqueda', sa.String(length=255), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('termino_busqueda')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen_producto')
    # ### end Alembic commands ###
