"""empty message

Revision ID: e3ae0fcaa6d8
Revises: d50fc3af5a0d
Create Date: 2025-12-06 19:39:24.154432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ae0fcaa6d8'
down_revision = 'd50fc3af5a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('url_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.VARCHAR(length=899), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
